export const categoryLabels: Record<
  string,
  Record<string, string>
> = {
  "20": {
    morning: "Morning",
    evening: "Evening",
    sleep: "Sleep",
    travel: "Travel",
    forgiveness: "Forgiveness",
    rizq: "Provision",
    anxiety: "Anxiety",
    knowledge: "Knowledge",
    family: "Family",
    general: "General",
  },
  "33": {
    morning: "Pagi",
    evening: "Petang",
    sleep: "Tidur",
    travel: "Perjalanan",
    forgiveness: "Istighfar",
    rizq: "Rezeki",
    anxiety: "Kecemasan",
    knowledge: "Ilmu",
    family: "Keluarga",
    general: "Umum",
  },
  "31": {
    morning: "Sabah",
    evening: "Akşam",
    sleep: "Uyku",
    travel: "Seyahat",
    forgiveness: "Bağışlanma",
    rizq: "Rızık",
    anxiety: "Kaygı",
    knowledge: "İlim",
    family: "Aile",
    general: "Genel",
  },
  "85": {
    morning: "Matin",
    evening: "Soir",
    sleep: "Sommeil",
    travel: "Voyage",
    forgiveness: "Pardon",
    rizq: "Subsistance",
    anxiety: "Anxiété",
    knowledge: "Savoir",
    family: "Famille",
    general: "Général",
  },
  "97": {
    morning: "صبح",
    evening: "شام",
    sleep: "سونا",
    travel: "سفر",
    forgiveness: "استغفار",
    rizq: "رزق",
    anxiety: "پریشانی",
    knowledge: "علم",
    family: "خاندان",
    general: "عام",
  },
};
